Repository FAST-gamsungcoding/FE_MiniProject, pull requests merged in 2023-12, with the labels that each got.

#91 [Feat] 예약 내역 페이지 스켈레톤 구현 및 보완
  src/app/(header)/(narrow-view)/reservation-list/_components/reservation-item/page.tsx
  src/app/(header)/(narrow-view)/reservation-list/_components/reservation-item/reservationItem.module.scss
  src/app/(header)/(narrow-view)/reservation-list/_components/reservation-skeleton/index.tsx
  src/app/(header)/(narrow-view)/reservation-list/reservationList.tsx
  src/components/layouts/loader/index.tsx
  src/components/layouts/loader/loader.module.scss
  src/components/layouts/loader/loaderType.ts
  src/components/layouts/skeleton/index.tsx
  src/components/layouts/skeleton/skeleton.module.scss
  src/components/layouts/skeleton/skeleton.stories.tsx
  src/components/layouts/skeleton/skeletonType.ts
  src/styles/_variables.scss
  src/utils/pxToRem.ts
Labels: feat

#94 [Refactor] 장바구니 페이지 오류 해결 및 보완
  src/app/(header)/(narrow-view)/cart/_components/cart-footer/cartFooter.stories.tsx
  src/app/(header)/(narrow-view)/cart/_components/cart-group/index.tsx
  src/app/(header)/(narrow-view)/cart/_components/cart-item/cartItem.module.scss
  src/app/(header)/(narrow-view)/cart/_components/cart-item/index.tsx
  src/app/(header)/(narrow-view)/cart/_components/cart-item/soldOutCartItem.tsx
  src/components/atoms/button/button.scss
  src/components/atoms/button/buttonType.ts
  src/components/atoms/button/index.tsx
  src/components/atoms/checkbox/checkboxType.ts
  src/components/atoms/checkbox/index.tsx
  src/hooks/cart/useCart.ts
Labels: fix, refactor

#95 [Feat] 장바구니 페이지 스켈레톤 구현
  src/app/(header)/(narrow-view)/cart/_components/cart-skeleton/index.tsx
  src/app/(header)/(narrow-view)/cart/cart.module.scss
  src/app/(header)/(narrow-view)/cart/cart.tsx
  src/hooks/cart/useCart.ts
Labels: feat

#97 [Refactor] 상세페이지 리팩토링
  src/api/rooms/index.ts
  src/api/rooms/roomsApiType.ts
  src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/carousel.module.scss
  src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/carouselType.ts
  src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/index.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/cart-modal/cartModal.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/cart-modal/cartModalType.ts
  src/app/(header)/(wide-view)/rooms/[id]/_component/custom-calendar/index.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/detail-page/detailPage.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/index.tsx
Labels: refactor

#103 [Style] 반응형 관련 mixin 추가
  src/Provider.tsx
  src/app/(header)/(wide-view)/main/main.module.scss
  src/styles/_common.scss
  src/styles/mobile.module.scss
Labels: style

#105 [Style] 장바구니 페이지 반응형 구현
  src/app/(header)/(narrow-view)/cart/_components/cart-footer/cartFooter.module.scss
  src/app/(header)/(narrow-view)/cart/_components/cart-group/cartGroup.module.scss
  src/app/(header)/(narrow-view)/cart/_components/cart-item/cartItem.module.scss
  src/app/(header)/(narrow-view)/cart/_components/cart-item/index.tsx
  src/app/(header)/(narrow-view)/cart/_components/cart-item/soldOutCartItem.tsx
  src/components/atoms/button/button.scss
  src/components/atoms/button/buttonType.ts
  src/components/atoms/text/index.tsx
  src/components/atoms/text/text.scss
Labels: style

#104 [Refactor] 회원가입 및 로그인 페이지 리팩토링 진행
  src/app/(non-header)/sign-in/_components/signInForm/index.tsx
  src/app/(non-header)/sign-up/_components/signUpForm/index.tsx
  src/components/atoms/input/index.tsx
  src/components/atoms/input/inputType.ts
  src/components/layouts/header/index.tsx
  src/constants/emailRegex.ts
  src/constants/regex.ts
  src/hooks/sign/signOutHandler.ts
  src/hooks/sign/signUpType.ts
  src/hooks/sign/useSignInForm.ts
  src/hooks/sign/useSignUpForm.ts
  src/recoil/.gitkeep
Labels: refactor

#101 [Refactor] 메인페이지 UI 개선 및 코드 가독성을 위한 리팩토링
  src/app/(header)/(wide-view)/main/_components/category-list/categoryListType.ts
  src/app/(header)/(wide-view)/main/_components/category-list/index.tsx
  src/app/(header)/(wide-view)/main/_components/category/categoryType.ts
  src/app/(header)/(wide-view)/main/_components/category/index.tsx
  src/app/(header)/(wide-view)/main/_components/item-list/itemList.module.scss
  src/app/(header)/(wide-view)/main/_components/item/item.module.scss
  src/app/(header)/(wide-view)/main/page.tsx
  src/constants/main.ts
  src/hooks/main/useMain.ts
Labels: refactor

#106 [Style] 주문 내역 확인하기 페이지 반응형 구현
  src/app/(header)/(narrow-view)/cart/_components/cart-group/cartGroup.module.scss
  src/app/(header)/(narrow-view)/cart/cart.module.scss
  src/app/(header)/(narrow-view)/cart/cart.tsx
  src/app/(header)/(narrow-view)/reservation-list/_components/reservation-item/page.tsx
  src/app/(header)/(narrow-view)/reservation-list/_components/reservation-item/reservationItem.module.scss
  src/app/(header)/(narrow-view)/reservation-list/_components/reservation-list-title/reservationListTitle.module.scss
  src/hooks/cart/useCart.ts
  src/hooks/cart/useSelect.ts
  src/recoil/selectedItem.ts
Labels: style

#107 [Feature] 비밀번호 보기 토글버튼 추가
  src/app/(non-header)/sign-in/_components/signInForm/index.tsx
  src/app/(non-header)/sign-up/_components/signUpForm/index.tsx
  src/components/atoms/input/index.tsx
  src/components/atoms/input/input.scss
  src/components/atoms/input/inputType.ts
  src/hooks/sign/useSignUpForm.ts
Labels: feat

#102 [Refactor] 예약하기/예약 확인하기 페이지 리팩토링
  src/app/(header)/(narrow-view)/reservation-check/_components/detail-contents/detailContents.module.scss
  src/app/(header)/(narrow-view)/reservation-check/_components/detail-contents/index.tsx
  src/app/(header)/(narrow-view)/reservation-check/_components/detail-titles/detailTitles.module.scss
  src/app/(header)/(narrow-view)/reservation-check/_components/detail-titles/index.tsx
  src/app/(header)/(narrow-view)/reservation-check/page.tsx
  src/app/(header)/(narrow-view)/reservation/_components/detail-contents/detailContents.module.scss
  src/app/(header)/(narrow-view)/reservation/_components/detail-contents/index.tsx
  src/app/(header)/(narrow-view)/reservation/_components/detail-titles/detailTitles.module.scss
  src/app/(header)/(narrow-view)/reservation/_components/detail-titles/index.tsx
  src/app/(header)/(narrow-view)/reservation/_components/purchase-info/index.tsx
  src/app/(header)/(narrow-view)/reservation/_components/reservation-items/index.tsx
  src/app/(header)/(narrow-view)/reservation/page.tsx
  src/app/(header)/(narrow-view)/reservation/reservation.module.scss
  src/components/atoms/button/button.scss
  src/components/atoms/input/input.scss
  src/components/atoms/input/inputType.ts
Labels: refactor

#108 [Refactor] : 상세페이지 리팩토링
  src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/carousel.module.scss
  src/app/(header)/(wide-view)/rooms/[id]/_component/carousel/index.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/custom-calendar/customCalendar.module.scss
  src/app/(header)/(wide-view)/rooms/[id]/_component/custom-calendar/index.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/detail-description/detailDescription.module.scss
  src/app/(header)/(wide-view)/rooms/[id]/_component/detail-description/detailDescription.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/detail-page/detailPage.module.scss
  src/app/(header)/(wide-view)/rooms/[id]/_component/detail-page/detailPage.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/index.tsx
  src/app/(header)/(wide-view)/rooms/[id]/_component/reservation/reservation.module.scss
Labels: refactor

#110 [Refactor] 코드 리뷰 반영
  src/app/(header)/(narrow-view)/reservation-check/_components/detail-titles/detailTitles.module.scss
  src/app/(header)/(narrow-view)/reservation/_components/detail-contents/detailContents.module.scss
  src/app/(header)/(narrow-view)/reservation/_components/detail-contents/index.tsx
  src/app/(header)/(narrow-view)/reservation/_components/detail-titles/detailTitles.module.scss
  src/app/(header)/(narrow-view)/reservation/_components/detail-titles/index.tsx
  src/app/(header)/(narrow-view)/reservation/page.tsx
Labels: refactor

#109 [Refactor] 메인페이지 코드 개선 및 카테고리 관련 UI 변경
  src/api/main/index.ts
  src/api/main/mainApiType.ts
  src/app/(header)/(wide-view)/main/_components/category/categoryType.ts
  src/app/(header)/(wide-view)/main/_components/category/index.tsx
  src/app/(header)/(wide-view)/main/_components/item-list/index.tsx
  src/app/(header)/(wide-view)/main/_components/item/index.tsx
  src/app/(header)/(wide-view)/main/_components/item/item.module.scss
  src/app/(header)/(wide-view)/main/page.tsx
  src/constants/main.ts
  src/hooks/main/useCategory.ts
  src/hooks/main/useMain.ts
  src/queries/main/index.ts
  src/styles/_reset.scss
Labels: refactor

#111 [Style] 로그인,회원가입 페이지 + Header 반응형 구현
  src/app/(non-header)/layout.tsx
  src/app/(non-header)/sign-in/_components/signInForm/signInForm.module.scss
  src/app/(non-header)/sign-up/_components/signUpForm/signUpForm.module.scss
  src/app/(non-header)/sign.module.scss
  src/app/(non-header)/signUp.module.scss
  src/components/atoms/input/input.scss
  src/components/atoms/logo/signLogo.module.scss
  src/components/layouts/footer/footer.module.scss
  src/components/layouts/header/header.module.scss
  src/components/layouts/header/index.tsx
  src/hooks/sign/useSignUpForm.ts
Labels: style

#112 [Refactor] 예약하기, 예약확인하기 반응형 수정
  src/app/(header)/(narrow-view)/reservation-check/page.tsx
  src/app/(header)/(narrow-view)/reservation-check/reservationCheck.module.scss
  src/app/(header)/(narrow-view)/reservation/page.tsx
  src/app/(header)/(narrow-view)/reservation/reservation.module.scss
  src/components/atoms/button/button.scss
  src/components/atoms/input/input.scss
Labels: refactor
